# Google Cloud Build configuration for HarvestHub FastAPI
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/harvesthub-pest-api:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/harvesthub-pest-api:latest",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/harvesthub-pest-api:$BUILD_ID"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/harvesthub-pest-api:latest"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "harvesthub-pest-api",
        "--image",
        "gcr.io/$PROJECT_ID/harvesthub-pest-api:$BUILD_ID",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "4Gi",
        "--cpu",
        "2",
        "--timeout",
        "300",
        "--concurrency",
        "10",
        "--max-instances",
        "3",
        "--set-env-vars",
        "ENVIRONMENT=production,DEBUG=false,LOG_LEVEL=info,WORKERS=1,TF_CPP_MIN_LOG_LEVEL=2,TF_ENABLE_ONEDNN_OPTS=0,PYTHONHASHSEED=0,TF_DETERMINISTIC_OPS=1,TF_CUDNN_DETERMINISTIC=1",
        "--port",
        "8000",
      ]

images:
  - "gcr.io/$PROJECT_ID/harvesthub-pest-api:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/harvesthub-pest-api:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
